/**
 * Builds the `ReportFact[]` sent to `POST /cases/{cid}/assistant/draft` from a report manifest.
 * Only structured metadata is ever sent (CLAUDE.md rule 6 — never frames, thumbnails or disk
 * bytes). Best-effort over whatever shaped arrays the manifest has, in a fixed order so ids are
 * stable for a given manifest:
 *   1. `deletion_findings[]`  -> one fact each (method, channel, frames recovered, confidence, actor)
 *   2. `evidence[]`           -> one fact each (id, file name, size, truncated SHA-256)
 *   3. `recordings_summary`   -> one fact with the recording count
 * If none of those exist (e.g. the stub-mode manifest) it falls back to a single fact describing
 * the report record itself. Ids are `fact_1`, `fact_2`, …
 */
import type { components } from "@/api/schema.gen";
import { isObj, objectList, type ReportManifest, type ReportRecord } from "./manifest";

export type ReportFact = components["schemas"]["ReportFact"];

const MAX_FACTS = 12;

function s(v: unknown): string | null {
  return typeof v === "string" && v.length > 0 ? v : null;
}
function n(v: unknown): number | null {
  return typeof v === "number" && Number.isFinite(v) ? v : null;
}

export function buildReportFacts(manifest: ReportManifest, record: ReportRecord): ReportFact[] {
  const texts: string[] = [];

  for (const d of objectList(manifest.deletion_findings)) {
    const parts: string[] = [`Deletion finding ${s(d.id) ?? "unnamed"}: method ${s(d.method) ?? "unknown"}`];
    const channel = n(d.channel);
    if (channel !== null) parts.push(`channel ${channel}`);
    const frames = n(d.frames_recovered);
    if (frames !== null) parts.push(`${frames} frames recovered`);
    const conf = n(d.confidence);
    if (conf !== null) parts.push(`confidence ${conf.toFixed(2)}`);
    const actor = s(d.actor);
    if (actor) parts.push(`actor ${actor}`);
    texts.push(`${parts.join(", ")}.`);
  }

  for (const e of objectList(manifest.evidence)) {
    const id = s(e.id) ?? "unnamed";
    const file = s(e.path)?.split("/").pop();
    const sha = s(e.sha256);
    const size = n(e.size_bytes);
    const parts: string[] = [`Evidence ${id}${file ? ` (${file})` : ""}`];
    if (size !== null) parts.push(`${size} bytes`);
    if (sha) parts.push(`SHA-256 begins ${sha.slice(0, 16)}`);
    texts.push(`${parts.join(", ")}.`);
  }

  if (isObj(manifest.recordings_summary)) {
    const count = n(manifest.recordings_summary.count);
    if (count !== null) texts.push(`The report covers ${count} recordings.`);
  }

  if (texts.length === 0) {
    texts.push(
      `Report ${record.id} for case ${record.case_id} was generated by ${record.examiner}; report SHA-256 begins ${record.report_sha256.slice(0, 16)}.`,
    );
  }

  return texts.slice(0, MAX_FACTS).map((text, i) => ({ id: `fact_${i + 1}`, text }));
}
