"""BSA Section 63 certificate data (docs/02-BACKEND.md §9 step 4).

Mirrors the structure of the Schedule to the Bharatiya Sakshya Adhiniyam,
2023 (Part A: completed by the party/person in charge of the device that
produced the electronic record; Part B: completed by the examiner). This
module only *prefills factual fields already present in the manifest* — it
never invents statutory wording beyond field labels and a neutral
declaration placeholder (CLAUDE.md instruction: "do not invent statutory
text beyond field labels and a neutral declaration placeholder").
"""

from __future__ import annotations

from typing import Any

TEMPLATE_NOTE = (
    "Template generated by Pramaan. Verify wording against the official "
    "Schedule before filing."
)

#: Neutral, non-statutory declaration placeholder — the examiner signs a
#: paper/blank line under this, it is not asserted on their behalf.
DECLARATION_PLACEHOLDER = (
    "I state that the particulars given above are, to the best of my "
    "knowledge and belief, true and that the electronic record described "
    "above was produced by the computer/device in the ordinary course of "
    "its use, and that during that period the device was operating properly "
    "or, if not, that any respect in which it was not operating properly or "
    "was out of operation did not affect the electronic record or the "
    "accuracy of its contents."
)


def _evidence_hash_lines(evidence: list[dict[str, Any]]) -> list[dict[str, str]]:
    """One line per evidence item per algorithm, full hash value, mono —
    docs/02-BACKEND.md §9 step 4: "hash values in full, mono, one per line,
    SHA-256 and MD5"."""
    lines: list[dict[str, str]] = []
    for item in evidence:
        label = item.get("path") or item.get("id", "")
        lines.append({"item": str(label), "algorithm": "SHA-256", "value": str(item["sha256"])})
        lines.append({"item": str(label), "algorithm": "MD5", "value": str(item["md5"])})
    return lines


def _make_model_serial(intake_details: dict[str, Any]) -> tuple[str, str]:
    make_model = str(intake_details.get("make_model_label") or "Not recorded at intake")
    serial = str(intake_details.get("serial_label") or "Not recorded at intake")
    return make_model, serial


def _how_produced(evidence: list[dict[str, Any]]) -> str:
    formats = sorted({str(e.get("format", "raw")) for e in evidence})
    return (
        "Duplicated from the seized storage device using a write-blocked "
        f"acquisition ({'/'.join(formats) if formats else 'raw'} image), "
        "verified by SHA-256/MD5 comparison against the source at intake "
        "(docs/02-BACKEND.md §5, SWGDE-aligned intake)."
    )


def build_certificate_data(manifest: dict[str, Any]) -> dict[str, Any]:
    """Build the Part A / Part B field data for the certificate template
    from an already-built manifest (``pramaan_reporting.manifest.build_manifest``).
    Every factual field is pre-filled from the manifest; signature, name,
    designation and date lines are always left blank for wet/digital signing.
    """
    case = manifest["case"]
    evidence = manifest["evidence"]
    clock_obs = manifest["clock_observations"]

    # Intake details (make/model/serial) are recorded once per image at
    # evidence registration as a ClockObservation.details blob
    # (apps.api.real.store._build_clock_observation) — take the first
    # "seizure"-sourced observation per image, if any.
    intake_by_image: dict[str, dict[str, Any]] = {}
    for obs in clock_obs:
        if obs.get("source") == "seizure" and obs.get("image_id") not in intake_by_image:
            intake_by_image[obs["image_id"]] = obs.get("details", {})

    part_a_items = []
    for item in evidence:
        make_model, serial = _make_model_serial(intake_by_image.get(item["id"], {}))
        part_a_items.append(
            {
                "evidence_id": item["id"],
                "identity": item.get("path", item["id"]),
                "make_model": make_model,
                "serial": serial,
                "how_produced": _how_produced([item]),
                "size_bytes": item["size_bytes"],
                "acquired_utc": item["acquired_utc"],
            }
        )

    examination_performed = [
        "Hash verification against the value recorded at acquisition",
        "Vendor/format identification (fingerprinting)",
        "Index parsing of the live recording table",
        "Recovery of unindexed/deleted footage by structural carving",
        "Frame-level indexing with per-frame integrity hashes",
        "Device log parsing (where the log region was present and parseable)",
        "Deletion-event analysis and reasoning",
        "Stream-copy clip extraction for representative recovered footage",
    ]

    return {
        "case_number": case.get("case_number", ""),
        "case_title": case.get("title", ""),
        "template_note": TEMPLATE_NOTE,
        "declaration_placeholder": DECLARATION_PLACEHOLDER,
        "part_a": {
            "records": part_a_items,
            "hash_lines": _evidence_hash_lines(evidence),
        },
        "part_b": {
            "examiner": manifest["examiner"],
            "lab": case.get("lab", ""),
            "examination_performed": examination_performed,
            "hash_lines": _evidence_hash_lines(evidence),
            "verification_note": (
                "Every hash value above can be independently reconstructed by "
                "re-hashing the referenced evidence file, and cross-checked "
                "against the chain-of-custody entry recorded at registration "
                f"(custody chain head hash: {manifest['custody'].get('head_hash', 'n/a')})."
            ),
        },
    }
