/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppDesignRouteImport } from './routes/_app/design'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppCasesIndexRouteImport } from './routes/_app/cases/index'
import { Route as AppCasesCidIndexRouteImport } from './routes/_app/cases/$cid/index'
import { Route as AppCasesCidCustodyRouteImport } from './routes/_app/cases/$cid/custody'
import { Route as AppCasesCidExportsRouteImport } from './routes/_app/cases/$cid/exports'
import { Route as AppCasesCidFindingsRouteImport } from './routes/_app/cases/$cid/findings'
import { Route as AppCasesCidRecordingsRouteImport } from './routes/_app/cases/$cid/recordings'
import { Route as AppCasesCidReportsRouteImport } from './routes/_app/cases/$cid/reports'
import { Route as AppCasesCidReviewRouteImport } from './routes/_app/cases/$cid/review'
import { Route as AppCasesCidEvidenceIndexRouteImport } from './routes/_app/cases/$cid/evidence/index'
import { Route as AppCasesCidEvidenceEidRouteImport } from './routes/_app/cases/$cid/evidence/$eid'
import { Route as AppCasesCidEvidenceNewRouteImport } from './routes/_app/cases/$cid/evidence/new'
import { Route as AppCasesCidFramesFidProveRouteImport } from './routes/_app/cases/$cid/frames/$fid/prove'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDesignRoute = AppDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCasesIndexRoute = AppCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCasesCidIndexRoute = AppCasesCidIndexRouteImport.update({
  id: '/cases/$cid/',
  path: '/cases/$cid/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCasesCidCustodyRoute = AppCasesCidCustodyRouteImport.update({
  id: '/cases/$cid/custody',
  path: '/cases/$cid/custody',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCasesCidExportsRoute = AppCasesCidExportsRouteImport.update({
  id: '/cases/$cid/exports',
  path: '/cases/$cid/exports',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCasesCidFindingsRoute = AppCasesCidFindingsRouteImport.update({
  id: '/cases/$cid/findings',
  path: '/cases/$cid/findings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCasesCidRecordingsRoute = AppCasesCidRecordingsRouteImport.update({
  id: '/cases/$cid/recordings',
  path: '/cases/$cid/recordings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCasesCidReportsRoute = AppCasesCidReportsRouteImport.update({
  id: '/cases/$cid/reports',
  path: '/cases/$cid/reports',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCasesCidReviewRoute = AppCasesCidReviewRouteImport.update({
  id: '/cases/$cid/review',
  path: '/cases/$cid/review',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCasesCidEvidenceIndexRoute =
  AppCasesCidEvidenceIndexRouteImport.update({
    id: '/cases/$cid/evidence/',
    path: '/cases/$cid/evidence/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppCasesCidEvidenceEidRoute = AppCasesCidEvidenceEidRouteImport.update({
  id: '/cases/$cid/evidence/$eid',
  path: '/cases/$cid/evidence/$eid',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCasesCidEvidenceNewRoute = AppCasesCidEvidenceNewRouteImport.update({
  id: '/cases/$cid/evidence/new',
  path: '/cases/$cid/evidence/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCasesCidFramesFidProveRoute =
  AppCasesCidFramesFidProveRouteImport.update({
    id: '/cases/$cid/frames/$fid/prove',
    path: '/cases/$cid/frames/$fid/prove',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/design': typeof AppDesignRoute
  '/settings': typeof AppSettingsRoute
  '/cases/': typeof AppCasesIndexRoute
  '/cases/$cid/custody': typeof AppCasesCidCustodyRoute
  '/cases/$cid/exports': typeof AppCasesCidExportsRoute
  '/cases/$cid/findings': typeof AppCasesCidFindingsRoute
  '/cases/$cid/recordings': typeof AppCasesCidRecordingsRoute
  '/cases/$cid/reports': typeof AppCasesCidReportsRoute
  '/cases/$cid/review': typeof AppCasesCidReviewRoute
  '/cases/$cid/': typeof AppCasesCidIndexRoute
  '/cases/$cid/evidence/$eid': typeof AppCasesCidEvidenceEidRoute
  '/cases/$cid/evidence/new': typeof AppCasesCidEvidenceNewRoute
  '/cases/$cid/evidence/': typeof AppCasesCidEvidenceIndexRoute
  '/cases/$cid/frames/$fid/prove': typeof AppCasesCidFramesFidProveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/design': typeof AppDesignRoute
  '/settings': typeof AppSettingsRoute
  '/cases': typeof AppCasesIndexRoute
  '/cases/$cid/custody': typeof AppCasesCidCustodyRoute
  '/cases/$cid/exports': typeof AppCasesCidExportsRoute
  '/cases/$cid/findings': typeof AppCasesCidFindingsRoute
  '/cases/$cid/recordings': typeof AppCasesCidRecordingsRoute
  '/cases/$cid/reports': typeof AppCasesCidReportsRoute
  '/cases/$cid/review': typeof AppCasesCidReviewRoute
  '/cases/$cid': typeof AppCasesCidIndexRoute
  '/cases/$cid/evidence/$eid': typeof AppCasesCidEvidenceEidRoute
  '/cases/$cid/evidence/new': typeof AppCasesCidEvidenceNewRoute
  '/cases/$cid/evidence': typeof AppCasesCidEvidenceIndexRoute
  '/cases/$cid/frames/$fid/prove': typeof AppCasesCidFramesFidProveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/design': typeof AppDesignRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/cases/': typeof AppCasesIndexRoute
  '/_app/cases/$cid/custody': typeof AppCasesCidCustodyRoute
  '/_app/cases/$cid/exports': typeof AppCasesCidExportsRoute
  '/_app/cases/$cid/findings': typeof AppCasesCidFindingsRoute
  '/_app/cases/$cid/recordings': typeof AppCasesCidRecordingsRoute
  '/_app/cases/$cid/reports': typeof AppCasesCidReportsRoute
  '/_app/cases/$cid/review': typeof AppCasesCidReviewRoute
  '/_app/cases/$cid/': typeof AppCasesCidIndexRoute
  '/_app/cases/$cid/evidence/$eid': typeof AppCasesCidEvidenceEidRoute
  '/_app/cases/$cid/evidence/new': typeof AppCasesCidEvidenceNewRoute
  '/_app/cases/$cid/evidence/': typeof AppCasesCidEvidenceIndexRoute
  '/_app/cases/$cid/frames/$fid/prove': typeof AppCasesCidFramesFidProveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/design'
    | '/settings'
    | '/cases/'
    | '/cases/$cid/custody'
    | '/cases/$cid/exports'
    | '/cases/$cid/findings'
    | '/cases/$cid/recordings'
    | '/cases/$cid/reports'
    | '/cases/$cid/review'
    | '/cases/$cid/'
    | '/cases/$cid/evidence/$eid'
    | '/cases/$cid/evidence/new'
    | '/cases/$cid/evidence/'
    | '/cases/$cid/frames/$fid/prove'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/design'
    | '/settings'
    | '/cases'
    | '/cases/$cid/custody'
    | '/cases/$cid/exports'
    | '/cases/$cid/findings'
    | '/cases/$cid/recordings'
    | '/cases/$cid/reports'
    | '/cases/$cid/review'
    | '/cases/$cid'
    | '/cases/$cid/evidence/$eid'
    | '/cases/$cid/evidence/new'
    | '/cases/$cid/evidence'
    | '/cases/$cid/frames/$fid/prove'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/design'
    | '/_app/settings'
    | '/_app/cases/'
    | '/_app/cases/$cid/custody'
    | '/_app/cases/$cid/exports'
    | '/_app/cases/$cid/findings'
    | '/_app/cases/$cid/recordings'
    | '/_app/cases/$cid/reports'
    | '/_app/cases/$cid/review'
    | '/_app/cases/$cid/'
    | '/_app/cases/$cid/evidence/$eid'
    | '/_app/cases/$cid/evidence/new'
    | '/_app/cases/$cid/evidence/'
    | '/_app/cases/$cid/frames/$fid/prove'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/design': {
      id: '/_app/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof AppDesignRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/cases/': {
      id: '/_app/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof AppCasesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/cases/$cid/': {
      id: '/_app/cases/$cid/'
      path: '/cases/$cid'
      fullPath: '/cases/$cid/'
      preLoaderRoute: typeof AppCasesCidIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/cases/$cid/custody': {
      id: '/_app/cases/$cid/custody'
      path: '/cases/$cid/custody'
      fullPath: '/cases/$cid/custody'
      preLoaderRoute: typeof AppCasesCidCustodyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/cases/$cid/exports': {
      id: '/_app/cases/$cid/exports'
      path: '/cases/$cid/exports'
      fullPath: '/cases/$cid/exports'
      preLoaderRoute: typeof AppCasesCidExportsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/cases/$cid/findings': {
      id: '/_app/cases/$cid/findings'
      path: '/cases/$cid/findings'
      fullPath: '/cases/$cid/findings'
      preLoaderRoute: typeof AppCasesCidFindingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/cases/$cid/recordings': {
      id: '/_app/cases/$cid/recordings'
      path: '/cases/$cid/recordings'
      fullPath: '/cases/$cid/recordings'
      preLoaderRoute: typeof AppCasesCidRecordingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/cases/$cid/reports': {
      id: '/_app/cases/$cid/reports'
      path: '/cases/$cid/reports'
      fullPath: '/cases/$cid/reports'
      preLoaderRoute: typeof AppCasesCidReportsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/cases/$cid/review': {
      id: '/_app/cases/$cid/review'
      path: '/cases/$cid/review'
      fullPath: '/cases/$cid/review'
      preLoaderRoute: typeof AppCasesCidReviewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/cases/$cid/evidence/': {
      id: '/_app/cases/$cid/evidence/'
      path: '/cases/$cid/evidence'
      fullPath: '/cases/$cid/evidence/'
      preLoaderRoute: typeof AppCasesCidEvidenceIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/cases/$cid/evidence/$eid': {
      id: '/_app/cases/$cid/evidence/$eid'
      path: '/cases/$cid/evidence/$eid'
      fullPath: '/cases/$cid/evidence/$eid'
      preLoaderRoute: typeof AppCasesCidEvidenceEidRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/cases/$cid/evidence/new': {
      id: '/_app/cases/$cid/evidence/new'
      path: '/cases/$cid/evidence/new'
      fullPath: '/cases/$cid/evidence/new'
      preLoaderRoute: typeof AppCasesCidEvidenceNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/cases/$cid/frames/$fid/prove': {
      id: '/_app/cases/$cid/frames/$fid/prove'
      path: '/cases/$cid/frames/$fid/prove'
      fullPath: '/cases/$cid/frames/$fid/prove'
      preLoaderRoute: typeof AppCasesCidFramesFidProveRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDesignRoute: typeof AppDesignRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppCasesIndexRoute: typeof AppCasesIndexRoute
  AppCasesCidCustodyRoute: typeof AppCasesCidCustodyRoute
  AppCasesCidExportsRoute: typeof AppCasesCidExportsRoute
  AppCasesCidFindingsRoute: typeof AppCasesCidFindingsRoute
  AppCasesCidRecordingsRoute: typeof AppCasesCidRecordingsRoute
  AppCasesCidReportsRoute: typeof AppCasesCidReportsRoute
  AppCasesCidReviewRoute: typeof AppCasesCidReviewRoute
  AppCasesCidIndexRoute: typeof AppCasesCidIndexRoute
  AppCasesCidEvidenceEidRoute: typeof AppCasesCidEvidenceEidRoute
  AppCasesCidEvidenceNewRoute: typeof AppCasesCidEvidenceNewRoute
  AppCasesCidEvidenceIndexRoute: typeof AppCasesCidEvidenceIndexRoute
  AppCasesCidFramesFidProveRoute: typeof AppCasesCidFramesFidProveRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDesignRoute: AppDesignRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppCasesIndexRoute: AppCasesIndexRoute,
  AppCasesCidCustodyRoute: AppCasesCidCustodyRoute,
  AppCasesCidExportsRoute: AppCasesCidExportsRoute,
  AppCasesCidFindingsRoute: AppCasesCidFindingsRoute,
  AppCasesCidRecordingsRoute: AppCasesCidRecordingsRoute,
  AppCasesCidReportsRoute: AppCasesCidReportsRoute,
  AppCasesCidReviewRoute: AppCasesCidReviewRoute,
  AppCasesCidIndexRoute: AppCasesCidIndexRoute,
  AppCasesCidEvidenceEidRoute: AppCasesCidEvidenceEidRoute,
  AppCasesCidEvidenceNewRoute: AppCasesCidEvidenceNewRoute,
  AppCasesCidEvidenceIndexRoute: AppCasesCidEvidenceIndexRoute,
  AppCasesCidFramesFidProveRoute: AppCasesCidFramesFidProveRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
