/**
 * Mock-video time mapping. Each channel's coverage in the demo case spans hours (see
 * review-fixtures.ts), but every mock clip (apps/web/public/mocks/clips/ch{1..4}.mp4) is a
 * short, deterministic 20s/10fps loop generated by ffmpeg (see docs/progress/F3a.md). This maps
 * a case-timeline position (normalised microseconds) onto a position inside that short clip so
 * scrubbing/playing the real case timeline drives real (looping) video playback.
 *
 * Real mode (once the backend serves actual per-recording clips) replaces this file's mapping
 * with a direct recording -> clip lookup; this module is mock-only and lives here, not in
 * src/mocks/, because it's presentation logic the video-grid component needs at render time.
 */
export interface ClipMapping {
  channel: number;
  url: string;
  /** Case-timeline window this clip stands in for, normalised microseconds. */
  coverageStartUs: number;
  coverageEndUs: number;
  clipDurationS: number;
}

/** us-in-case-timeline -> seconds-into-the-mock-clip, looping. */
export function mapUsToClipSeconds(us: number, mapping: ClipMapping): number {
  const span = Math.max(1, mapping.coverageEndUs - mapping.coverageStartUs);
  const offsetUs = ((us - mapping.coverageStartUs) % span + span) % span;
  const ratio = offsetUs / span;
  return ratio * mapping.clipDurationS;
}

/** Inverse of mapUsToClipSeconds's *rate*, used to convert clip-time deltas back into case-time
 * deltas while the leader tile is actually playing (so play direction/speed feels continuous). */
export function clipSecondsDeltaToUs(deltaS: number, mapping: ClipMapping): number {
  const span = Math.max(1, mapping.coverageEndUs - mapping.coverageStartUs);
  return (deltaS / mapping.clipDurationS) * span;
}
