"""Corpus-scale pipeline e2e on real synthetic DVR images (docs/02-BACKEND.md
§12 acceptance: "e2e on hiksim_format and dhsim_format marked `slow`; they
will pass once C2 lands; they must skip cleanly now if parsers/corpus are
missing").

``pramaan_formats``/``pramaan_recovery`` (task C2) did not exist yet when
this was written — only ``__init__.py`` stubs, no ``registry`` module and
no registered vendor parsers — so both parametrised cases skip themselves
rather than fail. Once C2 registers real ``hiksim``/``dhsim``
``VendorParser``s (via ``pramaan_formats.registry``), these start running
for real against ``corpus/images/`` (gitignored; generated by ``just
corpus`` — task Q1/Q2).
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

pytestmark = pytest.mark.slow

_CORPUS_IMAGES = Path(__file__).resolve().parents[2] / "corpus" / "images"
_CORPUS_TRUTH = Path(__file__).resolve().parents[2] / "corpus" / "truth"


def _corpus_image(name: str) -> Path | None:
    path = _CORPUS_IMAGES / name
    return path if path.is_file() else None


def _corpus_truth(name: str) -> dict[str, object] | None:
    path = _CORPUS_TRUTH / f"{name}.json"
    return json.loads(path.read_text(encoding="utf-8")) if path.is_file() else None


def _family_registered(family: str) -> bool:
    try:
        import pramaan_formats.registry as reg
    except ImportError:
        return False
    try:
        return reg.get(family) is not None
    except AttributeError:
        return False


def _intake_body() -> dict[str, str]:
    return {
        "seized_at_local": "2026-03-12T16:40:00+05:30",
        "dvr_displayed_time": "2026-03-12T16:45:12",
        "reference_time": "2026-03-12T16:40:00+05:30",
        "reference_source": "NTP phone clock",
        "timezone": "Asia/Kolkata",
        "make_model_label": "synthetic corpus device",
        "notes": "B2 corpus e2e (tests/backend/test_pipeline_corpus_slow.py)",
    }


@pytest.mark.parametrize(
    ("family", "image_name"),
    [
        ("hiksim", "hiksim_format.img"),
        ("dhsim", "dhsim_format.img"),
        # HWSIM (task C3/FIX-1): Tier A, real VendorParser + (once
        # registered — see `apps/worker/pramaan_worker/registry.py`'s
        # `_REAL_VENDOR_CARVER_NAMES`) real vendor carver for its deleted
        # round. `list_recordings`/`iter_frames` come straight from
        # `parse_index`, same as HIKSIM/DHSIM — no confirm step needed.
        ("hwsim", "hwsim_format.img"),
    ],
)
def test_scan_pipeline_e2e_on_corpus_image(
    real_client: TestClient, real_evidence_dir: Path, family: str, image_name: str
) -> None:
    image_src = _corpus_image(image_name)
    if image_src is None:
        pytest.skip(f"corpus/images/{image_name} not present (run `just corpus` — task Q1/Q2)")
    if not _family_registered(family):
        pytest.skip(f"pramaan_formats has no registered parser for family {family!r} yet (task C2)")

    dest = real_evidence_dir / image_name
    shutil.copy(image_src, dest)

    case = real_client.post(
        "/api/cases", json={"case_number": f"CR-CORPUS-{family.upper()}", "title": image_name}
    ).json()
    ev = real_client.post(
        f"/api/cases/{case['id']}/evidence",
        json={"path": str(dest), "label": image_name, "intake": _intake_body()},
    ).json()

    resp = real_client.post(f"/api/evidence/{ev['id']}/scan", json={})
    assert resp.status_code == 202, resp.text
    job = resp.json()
    assert job["status"] == "done", job
    assert all(s["status"] == "done" for s in job["stages"]), job["stages"]

    recordings = real_client.get(f"/api/cases/{case['id']}/recordings").json()
    assert len(recordings) > 0
    frames = real_client.get(f"/api/cases/{case['id']}/frames").json()
    assert len(frames) > 0

    # Prove-it over up to 100 frames (docs/02-BACKEND.md §12: "for 100
    # random frames, the hex endpoint's recomputed payload SHA-256 equals
    # the frame's stored hash").
    for frame in frames[:100]:
        hex_resp = real_client.get(f"/api/frames/{frame['frame_id']}/hex")
        assert hex_resp.status_code == 200, hex_resp.text
        assert hex_resp.json()["matches"] is True


def test_xsim_layout_confirm_enables_recordings(
    real_client: TestClient, real_reviewer_client: TestClient, real_evidence_dir: Path
) -> None:
    """XSIM (Tier B, no vendor signature above the Tier-A threshold —
    docs/01-FORENSIC-CORE.md §4.6/§4.8): ``/scan`` runs ``infer_layout`` for
    real (task C3) and discovers a layout, but ``parse_index`` has no
    family to key off of, so XSIM footage isn't listed as a recording
    until an examiner reviews and confirms the discovered layout (task
    FIX-1, docs/02-BACKEND.md §4: "Confirmation is audited"). A reviewer
    may not confirm one (docs/02-BACKEND.md §11); an examiner confirming
    persists the confirmation and re-indexes the image so its footage
    becomes listed (``recordings``) and playable (a live, non-deleted
    recording with frames attached).
    """
    image_src = _corpus_image("xsim_unknown.img")
    if image_src is None:
        pytest.skip("corpus/images/xsim_unknown.img not present (run `just corpus` — task Q1/Q2)")
    try:
        from pramaan_recovery.infer import infer_layout  # type: ignore[import-untyped] # noqa: F401
    except ImportError:
        pytest.skip("pramaan_recovery.infer not importable yet (task C3)")

    dest = real_evidence_dir / "xsim_unknown.img"
    shutil.copy(image_src, dest)

    case = real_client.post(
        "/api/cases", json={"case_number": "CR-CORPUS-XSIM", "title": "xsim_unknown.img"}
    ).json()
    ev = real_client.post(
        f"/api/cases/{case['id']}/evidence",
        json={"path": str(dest), "label": "xsim_unknown.img", "intake": _intake_body()},
    ).json()

    resp = real_client.post(f"/api/evidence/{ev['id']}/scan", json={})
    assert resp.status_code == 202, resp.text
    job = resp.json()
    assert job["status"] == "done", job
    assert all(s["status"] == "done" for s in job["stages"]), job["stages"]

    layout_resp = real_client.get(f"/api/evidence/{ev['id']}/inferred-layout")
    assert layout_resp.status_code == 200, layout_resp.text
    layout = layout_resp.json()
    assert layout["confirmed_by"] is None
    layout_id = layout["id"]

    forbidden = real_reviewer_client.post(f"/api/inferred-layouts/{layout_id}/confirm")
    assert forbidden.status_code == 403, forbidden.text
    # A reviewer's failed attempt must not have confirmed it anyway.
    still_unconfirmed = real_client.get(f"/api/evidence/{ev['id']}/inferred-layout").json()
    assert still_unconfirmed["confirmed_by"] is None

    confirm_resp = real_client.post(f"/api/inferred-layouts/{layout_id}/confirm")
    assert confirm_resp.status_code == 200, confirm_resp.text
    confirmed = confirm_resp.json()
    assert confirmed["id"] == layout_id
    assert confirmed["confirmed_by"] == "examiner"

    recordings = real_client.get(f"/api/cases/{case['id']}/recordings").json()
    assert len(recordings) > 0, "confirming the layout must list XSIM's footage as recordings"
    live = [r for r in recordings if not r["deleted"]]
    assert len(live) > 0, "at least one recording per channel must be listed as live/playable"

    frames = real_client.get(f"/api/cases/{case['id']}/frames").json()
    assert len(frames) > 0
    recording_ids = {r["id"] for r in recordings}
    assert any(f["recording_id"] in recording_ids for f in frames)

    # Confirming is itself an audited action (docs/02-BACKEND.md §8).
    audit = real_client.get(f"/api/cases/{case['id']}/audit").json()
    actions = [e["action"] for e in audit["items"]]
    assert "layout.confirmed" in actions


def test_xsim_format_confirm_populates_deletions_matching_truth(
    real_client: TestClient, real_evidence_dir: Path
) -> None:
    """Task FIX-12 (repro: docs/progress/FIX-11.md "Cross-workstream
    issues" #1, confirmed at the CORE level by docs/progress/FIX-7.md's own
    ``test_xsim_format_deletion_verdict``): confirming ``xsim_format.img``'s
    inferred (Tier B) layout via the real API must populate
    ``GET /cases/{cid}/deletions`` with one finding per channel,
    ``method="format"`` — matching ``corpus/truth/xsim_format.json`` — not
    stay empty forever the way it did before this task (the confirm-
    triggered reindex used to stop at ``clips``, never re-running
    ``deletion_verdict`` against the confirm-populated ``recordings``).
    """
    image_src = _corpus_image("xsim_format.img")
    if image_src is None:
        pytest.skip("corpus/images/xsim_format.img not present (run `just corpus` — task Q1/Q2)")
    truth = _corpus_truth("xsim_format")
    if truth is None:
        pytest.skip("corpus/truth/xsim_format.json not present (run `just corpus` — task Q1/Q2)")
    try:
        from pramaan_recovery.deletion import (  # type: ignore[import-untyped] # noqa: F401
            detect_deletions,
        )
        from pramaan_recovery.infer import infer_layout  # noqa: F401
    except ImportError:
        pytest.skip("pramaan_recovery not importable yet (task C3)")

    dest = real_evidence_dir / "xsim_format.img"
    shutil.copy(image_src, dest)

    case = real_client.post(
        "/api/cases", json={"case_number": "CR-CORPUS-XSIM-DEL", "title": "xsim_format.img"}
    ).json()
    ev = real_client.post(
        f"/api/cases/{case['id']}/evidence",
        json={"path": str(dest), "label": "xsim_format.img", "intake": _intake_body()},
    ).json()

    resp = real_client.post(f"/api/evidence/{ev['id']}/scan", json={})
    assert resp.status_code == 202, resp.text
    job = resp.json()
    assert job["status"] == "done", job
    assert all(s["status"] == "done" for s in job["stages"]), job["stages"]

    # Before confirmation: XSIM is Tier B, no live index yet, so deletions
    # (computed against an empty `recordings` table) must be empty — the
    # documented pre-confirmation state, not this task's bug.
    deletions_before = real_client.get(f"/api/cases/{case['id']}/deletions").json()
    assert deletions_before == []

    layout = real_client.get(f"/api/evidence/{ev['id']}/inferred-layout").json()
    assert layout["confirmed_by"] is None
    layout_id = layout["id"]

    confirm_resp = real_client.post(f"/api/inferred-layouts/{layout_id}/confirm")
    assert confirm_resp.status_code == 200, confirm_resp.text
    assert confirm_resp.json()["confirmed_by"] == "examiner"

    deletions = real_client.get(f"/api/cases/{case['id']}/deletions").json()
    truth_deletions = truth["deletions"]
    assert isinstance(truth_deletions, list)
    truth_channels = {d["channel"] for d in truth_deletions}
    assert len(deletions) == len(truth_deletions), deletions

    by_channel = {d["channel"]: d for d in deletions}
    assert set(by_channel) == truth_channels
    for truth_del in truth_deletions:
        finding = by_channel[truth_del["channel"]]
        assert finding["method"] == "format" == truth_del["method"], finding
        assert finding["actor"] == truth_del["actor"]  # truth: null on every channel

    # Re-confirming is a no-op (task FIX-4): still exactly one finding per
    # channel, never doubled.
    confirm_again = real_client.post(f"/api/inferred-layouts/{layout_id}/confirm")
    assert confirm_again.status_code == 200, confirm_again.text
    deletions_after_second_confirm = real_client.get(f"/api/cases/{case['id']}/deletions").json()
    assert len(deletions_after_second_confirm) == len(truth_deletions)
