"""Corpus-scale pipeline e2e on real synthetic DVR images (docs/02-BACKEND.md
§12 acceptance: "e2e on hiksim_format and dhsim_format marked `slow`; they
will pass once C2 lands; they must skip cleanly now if parsers/corpus are
missing").

``pramaan_formats``/``pramaan_recovery`` (task C2) did not exist yet when
this was written — only ``__init__.py`` stubs, no ``registry`` module and
no registered vendor parsers — so both parametrised cases skip themselves
rather than fail. Once C2 registers real ``hiksim``/``dhsim``
``VendorParser``s (via ``pramaan_formats.registry``), these start running
for real against ``corpus/images/`` (gitignored; generated by ``just
corpus`` — task Q1/Q2).
"""

from __future__ import annotations

import shutil
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

pytestmark = pytest.mark.slow

_CORPUS_IMAGES = Path(__file__).resolve().parents[2] / "corpus" / "images"


def _corpus_image(name: str) -> Path | None:
    path = _CORPUS_IMAGES / name
    return path if path.is_file() else None


def _family_registered(family: str) -> bool:
    try:
        import pramaan_formats.registry as reg  # type: ignore[import-untyped]
    except ImportError:
        return False
    try:
        return reg.get(family) is not None
    except AttributeError:
        return False


def _intake_body() -> dict[str, str]:
    return {
        "seized_at_local": "2026-03-12T16:40:00+05:30",
        "dvr_displayed_time": "2026-03-12T16:45:12",
        "reference_time": "2026-03-12T16:40:00+05:30",
        "reference_source": "NTP phone clock",
        "timezone": "Asia/Kolkata",
        "make_model_label": "synthetic corpus device",
        "notes": "B2 corpus e2e (tests/backend/test_pipeline_corpus_slow.py)",
    }


@pytest.mark.parametrize(
    ("family", "image_name"),
    [("hiksim", "hiksim_format.img"), ("dhsim", "dhsim_format.img")],
)
def test_scan_pipeline_e2e_on_corpus_image(
    real_client: TestClient, real_evidence_dir: Path, family: str, image_name: str
) -> None:
    image_src = _corpus_image(image_name)
    if image_src is None:
        pytest.skip(f"corpus/images/{image_name} not present (run `just corpus` — task Q1/Q2)")
    if not _family_registered(family):
        pytest.skip(f"pramaan_formats has no registered parser for family {family!r} yet (task C2)")

    dest = real_evidence_dir / image_name
    shutil.copy(image_src, dest)

    case = real_client.post(
        "/api/cases", json={"case_number": f"CR-CORPUS-{family.upper()}", "title": image_name}
    ).json()
    ev = real_client.post(
        f"/api/cases/{case['id']}/evidence",
        json={"path": str(dest), "label": image_name, "intake": _intake_body()},
    ).json()

    resp = real_client.post(f"/api/evidence/{ev['id']}/scan", json={})
    assert resp.status_code == 202, resp.text
    job = resp.json()
    assert job["status"] == "done", job
    assert all(s["status"] == "done" for s in job["stages"]), job["stages"]

    recordings = real_client.get(f"/api/cases/{case['id']}/recordings").json()
    assert len(recordings) > 0
    frames = real_client.get(f"/api/cases/{case['id']}/frames").json()
    assert len(frames) > 0

    # Prove-it over up to 100 frames (docs/02-BACKEND.md §12: "for 100
    # random frames, the hex endpoint's recomputed payload SHA-256 equals
    # the frame's stored hash").
    for frame in frames[:100]:
        hex_resp = real_client.get(f"/api/frames/{frame['frame_id']}/hex")
        assert hex_resp.status_code == 200, hex_resp.text
        assert hex_resp.json()["matches"] is True
