/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cases */
        get: operations["list_cases_api_cases_get"];
        put?: never;
        /** Create Case */
        post: operations["create_case_api_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{cid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case */
        get: operations["get_case_api_cases__cid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Case */
        patch: operations["patch_case_api_cases__cid__patch"];
        trace?: never;
    };
    "/api/cases/{cid}/analytics/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Analytics */
        post: operations["run_analytics_api_cases__cid__analytics_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{cid}/anchors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Anchors */
        get: operations["list_anchors_api_cases__cid__anchors_get"];
        put?: never;
        /** Create Anchor */
        post: operations["create_anchor_api_cases__cid__anchors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{cid}/assistant/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assistant Draft */
        post: operations["assistant_draft_api_cases__cid__assistant_draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{cid}/assistant/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assistant Query */
        post: operations["assistant_query_api_cases__cid__assistant_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{cid}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit */
        get: operations["list_audit_api_cases__cid__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{cid}/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify Audit */
        get: operations["verify_audit_api_cases__cid__audit_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{cid}/clock-models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Clock Models */
        get: operations["list_clock_models_api_cases__cid__clock_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{cid}/deletions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Deletions */
        get: operations["list_deletions_api_cases__cid__deletions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{cid}/detections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Detections */
        get: operations["list_detections_api_cases__cid__detections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{cid}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evidence */
        get: operations["list_evidence_api_cases__cid__evidence_get"];
        put?: never;
        /** Register Evidence */
        post: operations["register_evidence_api_cases__cid__evidence_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{cid}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Export */
        post: operations["create_export_api_cases__cid__exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{cid}/frames": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Frames */
        get: operations["list_frames_api_cases__cid__frames_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{cid}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_cases__cid__jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{cid}/log-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Log Events */
        get: operations["list_log_events_api_cases__cid__log_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{cid}/motion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Motion */
        get: operations["list_motion_api_cases__cid__motion_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{cid}/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Recordings */
        get: operations["list_recordings_api_cases__cid__recordings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{cid}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reports */
        get: operations["list_reports_api_cases__cid__reports_get"];
        put?: never;
        /** Create Report */
        post: operations["create_report_api_cases__cid__reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{cid}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Timeline */
        get: operations["get_timeline_api_cases__cid__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clips/{clip_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Clip */
        get: operations["stream_clip_api_clips__clip_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clock-models/{id}/override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Override Clock Model */
        post: operations["override_clock_model_api_clock_models__id__override_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/{eid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence */
        get: operations["get_evidence_api_evidence__eid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/{eid}/fingerprint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fingerprint */
        get: operations["fingerprint_api_evidence__eid__fingerprint_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/{eid}/inferred-layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Inferred Layout */
        get: operations["get_inferred_layout_api_evidence__eid__inferred_layout_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/{eid}/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan Evidence */
        post: operations["scan_evidence_api_evidence__eid__scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/{eid}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Evidence */
        post: operations["verify_evidence_api_evidence__eid__verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exports/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Export */
        post: operations["verify_export_api_exports_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exports/{xid}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export File */
        get: operations["export_file_api_exports__xid__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/frames/{fid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Frame */
        get: operations["get_frame_api_frames__fid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/frames/{fid}/hex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Frame Hex */
        get: operations["frame_hex_api_frames__fid__hex_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/frames/{fid}/thumb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Frame Thumb */
        get: operations["frame_thumb_api_frames__fid__thumb_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fs/browse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse */
        get: operations["browse_api_fs_browse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inferred-layouts/{lid}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Inferred Layout */
        post: operations["confirm_inferred_layout_api_inferred_layouts__lid__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{jid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__jid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Llm Usage */
        get: operations["llm_usage_api_llm_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{rid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recording */
        get: operations["get_recording_api_recordings__rid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{rid}/certificate.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report Certificate */
        get: operations["report_certificate_api_reports__rid__certificate_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{rid}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report Manifest */
        get: operations["report_manifest_api_reports__rid__manifest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{rid}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report Pdf */
        get: operations["report_pdf_api_reports__rid__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_system_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyticsRunRequest */
        AnalyticsRunRequest: {
            /** Evidence Id */
            evidence_id?: string | null;
            /** Stages */
            stages?: string[] | null;
        };
        /** AnalyticsRunResult */
        AnalyticsRunResult: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
        };
        /** Anchor */
        Anchor: {
            /**
             * Backend
             * @enum {string}
             */
            backend: "local" | "fabric";
            /** Case Id */
            case_id: string;
            /** From Seq */
            from_seq: number;
            /** Id */
            id: string;
            /** Lab Signature */
            lab_signature: string;
            /** Merkle Root */
            merkle_root: string;
            /** To Seq */
            to_seq: number;
            /** Ts Utc */
            ts_utc: string;
        };
        /** AnchorCreate */
        AnchorCreate: {
            /** Backend */
            backend?: ("local" | "fabric") | null;
        };
        /** AssistantDraftRequest */
        AssistantDraftRequest: {
            /** Facts */
            facts: components["schemas"]["ReportFact"][];
        };
        /** AssistantQueryRequest */
        AssistantQueryRequest: {
            /** Question */
            question: string;
        };
        /** AssistantQueryResponse */
        AssistantQueryResponse: {
            filter: components["schemas"]["EvidenceSearchFilter"];
            /** Result Count */
            result_count: number;
            /** Results */
            results: {
                [key: string]: unknown;
            }[];
        };
        /** AuditEntry */
        AuditEntry: {
            /** Action */
            action: string;
            /** Actor */
            actor: string;
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /** Entry Hash */
            entry_hash: string;
            /** Object Id */
            object_id: string;
            /** Object Type */
            object_type: string;
            /** Payload Sha256 */
            payload_sha256: string | null;
            /** Prev Hash */
            prev_hash: string | null;
            /** Role */
            role: string;
            /** Seq */
            seq: number;
            /** Signature */
            signature: string;
            /** Ts Utc */
            ts_utc: string;
        };
        /** AuditVerifyResult */
        AuditVerifyResult: {
            /** First Bad Seq */
            first_bad_seq: number | null;
            /** Head Hash */
            head_hash: string | null;
            /** Length */
            length: number;
            /** Ok */
            ok: boolean;
        };
        /** Body_verify_export_api_exports_verify_post */
        Body_verify_export_api_exports_verify_post: {
            /** File */
            file: string;
        };
        /** ByteRange */
        ByteRange: {
            /** Length */
            length: number;
            /** Offset */
            offset: number;
        };
        /** Case */
        Case: {
            /** Case Number */
            case_number: string;
            /** Created Utc */
            created_utc: string;
            /** Fir Reference */
            fir_reference: string | null;
            /** Id */
            id: string;
            /** Lab */
            lab: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "closed" | "archived";
            /** Title */
            title: string;
            /** Updated Utc */
            updated_utc: string;
        };
        /** CaseCreate */
        CaseCreate: {
            /** Case Number */
            case_number: string;
            /** Fir Reference */
            fir_reference?: string | null;
            /** Lab */
            lab?: string | null;
            /** Title */
            title: string;
        };
        /** CasePatch */
        CasePatch: {
            /** Fir Reference */
            fir_reference?: string | null;
            /** Lab */
            lab?: string | null;
            /** Status */
            status?: ("open" | "closed" | "archived") | null;
            /** Title */
            title?: string | null;
        };
        /** ChannelClockSummary */
        ChannelClockSummary: {
            /** Confidence */
            confidence: number;
            /** Summary */
            summary: string;
        };
        /** ChannelTimeline */
        ChannelTimeline: {
            /** Channel */
            channel: number;
            clock: components["schemas"]["ChannelClockSummary"];
            /** Color Token */
            color_token: string;
            /** Coverage */
            coverage: [
                number,
                number,
                "index" | "carved" | "inferred"
            ][];
            /** Deleted */
            deleted: [
                number,
                number,
                string
            ][];
            /** Image Id */
            image_id: string;
            /** Label */
            label: string;
            /** Motion */
            motion: [
                number,
                number
            ][];
        };
        /** ClockModel */
        ClockModel: {
            /** Channel */
            channel: number | null;
            /** Confidence */
            confidence: number;
            /** Id */
            id: string;
            /** Image Id */
            image_id: string;
            /** Method */
            method: string;
            /** Osd Offset Us */
            osd_offset_us: number | null;
            /** Overridden By */
            overridden_by: string | null;
            /** Residual Ms */
            residual_ms: number;
            /** Segments */
            segments: components["schemas"]["ClockSegment"][];
        };
        /** ClockOverrideRequest */
        ClockOverrideRequest: {
            /** Offset Us */
            offset_us?: number | null;
            /** Reason */
            reason: string;
        };
        /** ClockSegment */
        ClockSegment: {
            /** From Device Us */
            from_device_us: number | null;
            /** Offset Us */
            offset_us: number;
            /** To Device Us */
            to_device_us: number | null;
        };
        /** DeletionFinding */
        DeletionFinding: {
            /** Action Ts Us */
            action_ts_us: number | null;
            /** Actor */
            actor: string | null;
            /** Bytes Recovered */
            bytes_recovered: number;
            /** Channel */
            channel: number | null;
            /** Confidence */
            confidence: number;
            /** End Ts Us */
            end_ts_us: number;
            /** Evidence Refs */
            evidence_refs: string[];
            /** Frames Recovered */
            frames_recovered: number;
            /** Id */
            id: string;
            /** Image Id */
            image_id: string;
            /**
             * Method
             * @enum {string}
             */
            method: "format" | "expiry" | "overwrite" | "unknown";
            /** Reasons */
            reasons: string[];
            /** Start Ts Us */
            start_ts_us: number;
        };
        /** Detection */
        Detection: {
            /** Bbox */
            bbox: [
                number,
                number,
                number,
                number
            ];
            /**
             * Cls
             * @enum {string}
             */
            cls: "person" | "vehicle" | "two_wheeler" | "other";
            /** Derived From */
            derived_from: string;
            /** Frame Id */
            frame_id: string;
            /** Id */
            id: string;
            /** Model */
            model: string;
            /** Score */
            score: number;
        };
        /** DraftSentenceOut */
        DraftSentenceOut: {
            /** Evidence Ids */
            evidence_ids: string[];
            /** Text */
            text: string;
        };
        /** EvidenceImage */
        EvidenceImage: {
            /** Acquired Utc */
            acquired_utc: string;
            /**
             * Format
             * @enum {string}
             */
            format: "raw" | "e01";
            /** Id */
            id: string;
            /** Md5 */
            md5: string;
            /** Path */
            path: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /** Verified */
            verified: boolean;
        };
        /** EvidenceRegister */
        EvidenceRegister: {
            intake: components["schemas"]["SwgdeIntake"];
            /** Label */
            label: string;
            /** Path */
            path: string;
        };
        /**
         * EvidenceSearchFilter
         * @description Arguments the model must supply to ``search_evidence``. Field names
         *     and semantics match docs/03-AI-TIMELINE.md §8.3.1 exactly, and this is
         *     the same shape ``apps/api/pramaan_api/routers/assistant.py`` exposes in
         *     ``AssistantQueryResponse.filter`` — the router imports this class
         *     instead of redefining it.
         */
        EvidenceSearchFilter: {
            /** Channels */
            channels?: number[] | null;
            /** Deleted Only */
            deleted_only?: boolean | null;
            /** Detection Class */
            detection_class?: string | null;
            /** From Ist */
            from_ist?: string | null;
            /** Log Kind */
            log_kind?: string | null;
            /** Motion Min */
            motion_min?: number | null;
            /** Source */
            source?: string | null;
            /** Text */
            text?: string | null;
            /** To Ist */
            to_ist?: string | null;
        };
        /** ExportCreate */
        ExportCreate: {
            /** Channel */
            channel?: number | null;
            /** From Norm Us */
            from_norm_us?: number | null;
            /** Recording Id */
            recording_id?: string | null;
            /** To Norm Us */
            to_norm_us?: number | null;
        };
        /** ExportRecord */
        ExportRecord: {
            /** Case Id */
            case_id: string;
            /** Channel */
            channel: number | null;
            /** Created Utc */
            created_utc: string;
            /** Examiner */
            examiner: string;
            /** File Path */
            file_path: string;
            /** From Norm Us */
            from_norm_us: number | null;
            /** Id */
            id: string;
            /** Manifest Sha256 */
            manifest_sha256: string;
            /** Recording Id */
            recording_id: string | null;
            /** Signature Path */
            signature_path: string;
            /** To Norm Us */
            to_norm_us: number | null;
        };
        /** ExportVerifyResult */
        ExportVerifyResult: {
            /** Manifest */
            manifest: {
                [key: string]: unknown;
            };
            /** Signature Valid */
            signature_valid: boolean;
            /** Source Matches Registered Evidence */
            source_matches_registered_evidence: boolean;
        };
        /** FrameRef */
        FrameRef: {
            /** Channel */
            channel: number | null;
            /**
             * Codec
             * @enum {string}
             */
            codec: "h264" | "h265";
            /** Deleted */
            deleted: boolean;
            /** Frame Id */
            frame_id: string;
            /**
             * Frame Type
             * @enum {string}
             */
            frame_type: "I" | "P" | "B" | "SPS" | "PPS" | "VPS" | "SEI" | "other";
            /** Header Offset */
            header_offset: number | null;
            /** Height */
            height: number | null;
            /** Image Id */
            image_id: string;
            /** Payload Len */
            payload_len: number;
            /** Payload Offset */
            payload_offset: number;
            /** Recording Id */
            recording_id: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "index" | "carved" | "inferred";
            /** Stream */
            stream: string | null;
            /** Ts Header Us */
            ts_header_us: number | null;
            /** Ts Index Us */
            ts_index_us: number | null;
            /** Width */
            width: number | null;
        };
        /** FsEntry */
        FsEntry: {
            /** Is Dir */
            is_dir: boolean;
            /** Looks Like Image */
            looks_like_image: boolean;
            /** Modified Utc */
            modified_utc: string | null;
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Size Bytes */
            size_bytes: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthStatus */
        HealthStatus: {
            /** Fabric */
            fabric: boolean;
            /** Ffmpeg */
            ffmpeg: boolean;
            /** Llm Enabled */
            llm_enabled: boolean;
            /** Pyewf */
            pyewf: boolean;
            /**
             * Scanner Backend
             * @enum {string}
             */
            scanner_backend: "rust" | "python";
            /** Stub Mode */
            stub_mode: boolean;
            /** Weasyprint */
            weasyprint: boolean;
        };
        /** HexView */
        HexView: {
            /** After */
            after: number;
            /** Annotations */
            annotations: {
                [key: string]: unknown;
            }[];
            /** Before */
            before: number;
            /** Bytes B64 */
            bytes_b64: string;
            /** Frame Id */
            frame_id: string;
            /** Matches */
            matches: boolean;
            /** Offset */
            offset: number;
            /** Payload Sha256 Recomputed */
            payload_sha256_recomputed: string;
            /** Payload Sha256 Stored */
            payload_sha256_stored: string;
        };
        /** InferredField */
        InferredField: {
            /** Confidence */
            confidence: number;
            /**
             * Endian
             * @enum {string}
             */
            endian: "le" | "be";
            /**
             * Name
             * @enum {string}
             */
            name: "magic" | "channel" | "timestamp" | "length" | "sequence" | "flags" | "unknown";
            /** Offset */
            offset: number;
            /** Support */
            support: number;
            /**
             * Unit
             * @default none
             * @enum {string}
             */
            unit: "s" | "ms" | "us" | "none";
            /** Width */
            width: number;
        };
        /** InferredLayout */
        InferredLayout: {
            /**
             * Codec
             * @enum {string}
             */
            codec: "h264" | "h265";
            /** Confirmed By */
            confirmed_by: string | null;
            /** Fields */
            fields: components["schemas"]["InferredField"][];
            /** Header Len */
            header_len: number;
            /** Id */
            id: string;
            /** Image Id */
            image_id: string;
            /** Magic */
            magic: string | null;
        };
        /** Job */
        Job: {
            /** Case Id */
            case_id: string;
            /** Created Utc */
            created_utc: string;
            /** Evidence Id */
            evidence_id: string | null;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "scan" | "verify" | "report" | "export";
            /** Log Lines */
            log_lines: string[];
            /** Pct */
            pct: number;
            /** Stages */
            stages: components["schemas"]["JobStage"][];
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "done" | "failed";
            /** Updated Utc */
            updated_utc: string;
        };
        /** JobStage */
        JobStage: {
            /** Message */
            message?: string | null;
            /** Name */
            name: string;
            /** Pct */
            pct: number;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "done" | "failed" | "skipped";
        };
        /** LlmUsageEntry */
        LlmUsageEntry: {
            /** Cost Usd */
            cost_usd: number;
            /** Created Utc */
            created_utc: string;
            /** Id */
            id: string;
            /** Input Tokens */
            input_tokens: number;
            /** Model */
            model: string;
            /** Output Tokens */
            output_tokens: number;
            /** Prompt Sha256 */
            prompt_sha256: string;
            /** Response Sha256 */
            response_sha256: string;
        };
        /** LogEvent */
        LogEvent: {
            /** Channel */
            channel: number | null;
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /** Image Id */
            image_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "login" | "logout" | "playback" | "export" | "hdd_format" | "time_change" | "config_change" | "power_on" | "other";
            /** Offset */
            offset: number;
            /** Ts Device Us */
            ts_device_us: number;
            /** User */
            user: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** Me */
        Me: {
            /** Display Name */
            display_name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "examiner" | "reviewer" | "admin";
            /** Username */
            username: string;
        };
        /** MotionSegment */
        MotionSegment: {
            /** Channel */
            channel: number;
            /** End Norm Us */
            end_norm_us: number;
            /** Frames */
            frames: number;
            /** Id */
            id: string;
            /** Image Id */
            image_id: string;
            /** Peak Score */
            peak_score: number;
            /** Start Norm Us */
            start_norm_us: number;
        };
        /** Page[AuditEntry] */
        Page_AuditEntry_: {
            /** Items */
            items: components["schemas"]["AuditEntry"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Recording */
        Recording: {
            /** Byte Ranges */
            byte_ranges: components["schemas"]["ByteRange"][];
            /** Channel */
            channel: number;
            /** Deleted */
            deleted: boolean;
            /** End Ts Us */
            end_ts_us: number | null;
            /** Id */
            id: string;
            /** Image Id */
            image_id: string;
            /**
             * Source
             * @enum {string}
             */
            source: "index" | "carved" | "inferred";
            /** Start Ts Us */
            start_ts_us: number | null;
            /**
             * Stream
             * @enum {string}
             */
            stream: "main" | "sub";
        };
        /** ReportCreate */
        ReportCreate: {
            /**
             * Include Thumbnails
             * @default true
             */
            include_thumbnails: boolean;
        };
        /**
         * ReportFact
         * @description One fact from the report manifest (docs/03-AI-TIMELINE.md §8.3.2).
         */
        ReportFact: {
            /** Id */
            id: string;
            /** Text */
            text: string;
        };
        /** ReportRecord */
        ReportRecord: {
            /** Case Id */
            case_id: string;
            /** Certificate Path */
            certificate_path: string;
            /** Created Utc */
            created_utc: string;
            /** Examiner */
            examiner: string;
            /** Id */
            id: string;
            /** Manifest Path */
            manifest_path: string;
            /** Pdf Path */
            pdf_path: string;
            /** Report Sha256 */
            report_sha256: string;
        };
        /** ScanRequest */
        ScanRequest: {
            /**
             * Options
             * @default {}
             */
            options: {
                [key: string]: unknown;
            };
            /** Stages */
            stages?: string[] | null;
        };
        /** SearchResult */
        SearchResult: {
            /** Case Id */
            case_id: string;
            /** Detail */
            detail: string;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "case" | "evidence" | "recording" | "frame" | "finding";
            /** Label */
            label: string;
        };
        /** SwgdeIntake */
        SwgdeIntake: {
            /** Dvr Displayed Time */
            dvr_displayed_time: string;
            /** Make Model Label */
            make_model_label?: string | null;
            /** Notes */
            notes?: string | null;
            /** Reference Source */
            reference_source: string;
            /** Reference Time */
            reference_time: string;
            /** Seized At Local */
            seized_at_local: string;
            /** Serial Label */
            serial_label?: string | null;
            /** Timezone */
            timezone: string;
            /** Write Blocker */
            write_blocker?: string | null;
        };
        /** TimelineEvent */
        TimelineEvent: {
            /** Channels */
            channels: number[];
            /** End */
            end: number;
            /** Kind */
            kind: string;
            /** Start */
            start: number;
        };
        /** TimelineMarker */
        TimelineMarker: {
            /** Kind */
            kind: string;
            /** Log Event Id */
            log_event_id: string;
            /** Ts Norm Us */
            ts_norm_us: number;
            /** User */
            user: string | null;
        };
        /** TimelineResponse */
        TimelineResponse: {
            /** Channels */
            channels: components["schemas"]["ChannelTimeline"][];
            /** Events */
            events: components["schemas"]["TimelineEvent"][];
            /** Markers */
            markers: components["schemas"]["TimelineMarker"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VendorMatch */
        VendorMatch: {
            /** Confidence */
            confidence: number;
            /** Display Name */
            display_name: string;
            /** Evidence */
            evidence: string[];
            /** Family */
            family: string;
            /** Fs Version */
            fs_version: string | null;
            /** Model */
            model: string | null;
            /** Platform */
            platform: string | null;
            /** Serial */
            serial: string | null;
            /**
             * Tier
             * @enum {string}
             */
            tier: "A" | "B" | "C";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_cases_api_cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"][];
                };
            };
        };
    };
    create_case_api_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_api_cases__cid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_case_api_cases__cid__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CasePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_analytics_api_cases__cid__analytics_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyticsRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsRunResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_anchors_api_cases__cid__anchors_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Anchor"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_anchor_api_cases__cid__anchors_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnchorCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Anchor"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assistant_draft_api_cases__cid__assistant_draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistantDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftSentenceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assistant_query_api_cases__cid__assistant_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistantQueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantQueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_api_cases__cid__audit_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number | null;
            };
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AuditEntry_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_audit_api_cases__cid__audit_verify_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditVerifyResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_clock_models_api_cases__cid__clock_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClockModel"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_deletions_api_cases__cid__deletions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletionFinding"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_detections_api_cases__cid__detections_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detection"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evidence_api_cases__cid__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceImage"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_evidence_api_cases__cid__evidence_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvidenceRegister"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceImage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_export_api_cases__cid__exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_frames_api_cases__cid__frames_get: {
        parameters: {
            query?: {
                channel?: number | null;
                source?: ("index" | "carved" | "inferred") | null;
                deleted?: boolean | null;
                frame_type?: string | null;
                from?: number | null;
                to?: number | null;
                limit?: number;
            };
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameRef"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_cases__cid__jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_log_events_api_cases__cid__log_events_get: {
        parameters: {
            query?: {
                kind?: string | null;
            };
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_motion_api_cases__cid__motion_get: {
        parameters: {
            query?: {
                channel?: number | null;
            };
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MotionSegment"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recordings_api_cases__cid__recordings_get: {
        parameters: {
            query?: {
                channel?: number | null;
                source?: ("index" | "carved" | "inferred") | null;
                deleted?: boolean | null;
                from?: number | null;
                to?: number | null;
            };
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recording"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reports_api_cases__cid__reports_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_report_api_cases__cid__reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_timeline_api_cases__cid__timeline_get: {
        parameters: {
            query?: {
                from?: number | null;
                to?: number | null;
                bucket_s?: number;
            };
            header?: never;
            path: {
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_clip_api_clips__clip_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    override_clock_model_api_clock_models__id__override_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClockOverrideRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClockModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_api_evidence__eid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceImage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fingerprint_api_evidence__eid__fingerprint_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VendorMatch"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_inferred_layout_api_evidence__eid__inferred_layout_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InferredLayout"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_evidence_api_evidence__eid__scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_evidence_api_evidence__eid__verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_export_api_exports_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_verify_export_api_exports_verify_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportVerifyResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_file_api_exports__xid__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                xid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_frame_api_frames__fid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameRef"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    frame_hex_api_frames__fid__hex_get: {
        parameters: {
            query?: {
                before?: number;
                after?: number;
            };
            header?: never;
            path: {
                fid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HexView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    frame_thumb_api_frames__fid__thumb_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    browse_api_fs_browse_get: {
        parameters: {
            query?: {
                path?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FsEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_inferred_layout_api_inferred_layouts__lid__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InferredLayout"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__jid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    llm_usage_api_llm_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmUsageEntry"][];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    get_recording_api_recordings__rid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recording"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_certificate_api_reports__rid__certificate_pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_manifest_api_reports__rid__manifest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_pdf_api_reports__rid__pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_system_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
}
